import type { Metadata } from 'next';
import { Inter, Nunito } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/utils/auth';
import QueryClientProvider from '@/components/providers/query';

import SessionProvider from '@/components/providers/session';

const inter = Inter({ subsets: ['latin'] });
const nunito = Nunito({
  subsets: ['cyrillic', 'latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
});

export const metadata: Metadata = {
  title: 'Flex',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="ru">
      <body className={`${nunito.className} antialiased`}>
        <QueryClientProvider>
          <SessionProvider session={session}>
            <Toaster richColors />
            {children}
          </SessionProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
